name: Aloha Carioca
favicon: null
layout_spectrum: 0.51105
typography_spectrum: 0.3906028054188937
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#90e4fe'
    - '#010101'
    - '#be6a3e'
    - '#e79f65'
    - '#4f2d22'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.625
  rhythmicContrast: 0.6109609368722886
purpose: []
